### PR TITLE
Feature/custom subscribe

### PR DESCRIPTION
**Pull request by shams-ahmed**
**Fixes:**
- Uncalled disconnect when there socket issues
- Removed force wraps to prevent crashes
- Crash when converting model to JSON in new model
- Uncalled messages delegate method
- Pending subscriptions were not removed if socket errored out 

**Features/Improvements:**
- Added configurable timeout advice 
- Read/Write multi-threading
- Moved to enum based solution for Faye models 
- Helper methods to remove subscriptions
- Made client Id public to allow it to change i.e when we reconnecting Faye send a new iD
- Resubscribe to pending subscription timer
- Move to a model based solution for all subscriptions 
- Ping/Pong Faye socket

**General:**
- Refactored code base to use external extension 
- Cleaner console logs
- CocoaPods update
- XCode 7 updates

### CODE REVIEW

**Comment by hamin** [comment]
@shams-ahmed wow lots of good stuff. Gimme a few days to go over everything...thanks again :)

**Comment by shams-ahmed** [comment]
@hamin Please do so... It would be nice to get a second view.

**Comment by hamin** [comment]
@shams-ahmed sorry this took so long, just merged the changes

**Comment by hamin** [comment]
@shams-ahmed I forgot to mention one thing I had written down in my notes a while ago when first reviewing this. Check out this issue https://github.com/hamin/FayeSwift/issues/22 Thinking we can just use GCD lock queues there instead. Trying to remove any objc dependencies since one of my goals is to get this running on server side swift at some point. I wasn't sure if you had a specific need to do this in an app. Let's take further discussion over to https://github.com/hamin/FayeSwift/issues/22

**Pull request merged**
